### PR TITLE
Disable "react/prefer-stateless-function"

### PR DESCRIPTION
**Pull request by brandonc**
...because component consistency is valuable and many components may start as very simple but are presumed to grow in complexity later

### CODE REVIEW

**Comment by pk-nb** [comment]
I'm good with this: Functional components are still (of course) fine, but this helps with components that might just have a render method. The perf tradeoff is very minimal so I don't think enforcing this is worth it.

**Comment by derekclee** [comment]
I like this change too.

**Comment by Fireworks** [comment]
:+1:

**Review by dcroberts — APPROVED** [review]
👍

**Comment by NCSkoglund** [comment]
👍

**Comment by charliecorrigan** [comment]
👍

**Review by adsteel — APPROVED** [review]

**Pull request merged**
