### PR TITLE
do not enforce regex style

### PR DESCRIPTION
**Pull request by adsteel**

### CODE REVIEW

**Review by ianhenrysmith — APPROVED** [review]
🙏

**Review by mhuggins — APPROVED** [review]

**Comment by willmore** [comment]
@adsteel can we merge this?

**Comment by adsteel** [comment]
@aesnyder @pk-nb @derekclee @bwebster any concerns with merging this?

**Review by derekclee — APPROVED** [review]

**Comment by pk-nb** [comment]
:+1: ship it

**Pull request merged**
